export const INICIANDO_SESION = 'INICIANDO_SESION';
export const INICIO_SESION_EXITO = 'INICIO_SESION_EXITO';
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR';

export const CERRANDO_SESION = 'CERRANDO_SESION';
export const CERRANDO_SESION_EXITO = 'CERRANDO_SESION_EXITO';
export const CERRANDO_SESION_ERROR = 'CERRANDO_SESION_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const USUARIO_AUTENTICADO_ERROR = 'USUARIO_AUTENTICADO_ERROR';

export const CREANDO_USUARIO = 'CREANDO_USUARIO';
export const CREANDO_USUARIO_EXITO = 'CREANDO_USUARIO_EXITO';
export const CREANDO_USUARIO_ERROR = 'CREANDO_USUARIO_ERROR';

//notas
export const CARGANDO_NOTAS = 'CARGANDO_NOTAS';
export const CARGANDO_NOTAS_EXITO = 'CARGANDO_NOTAS_EXITO';
export const CARGANDO_NOTAS_ERROR = 'CARGANDO_NOTAS_ERROR';

export const OBTENER_NOTA = 'OBTENER_NOTA';
export const OBTENER_NOTA_EXITO = 'OBTENER_NOTA_EXITO';
export const OBTENER_NOTA_ERROR = 'OBTENER_NOTA_ERROR';

export const EDITANDO_NOTA = 'EDITANDO_NOTA';
export const EDITAR_NOTA_EXITO = 'EDITAR_NOTA_EXITO';
export const EDITAR_NOTA_ERROR = 'EDITAR_NOTA_ERROR';

export const CREANDO_NOTA = 'CREANDO_NOTA';
export const CREANDO_NOTA_ERROR = 'CREANDO_NOTA_ERROR';
export const CREANDO_NOTA_EXITO  = 'CREANDO_NOTA_EXITO';

export const ELIMINANDO_NOTA = 'ELIMINANDO_NOTA';
export const ELIMINANDO_NOTA_EXITO = 'ELIMINANDO_NOTA_EXITO';
export const ELIMINANDO_NOTA_ERROR = 'ELIMINANDO_NOTA_ERROR';
